name: learnifyapp
description: "A new Flutter project."


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  firebase_database: ^11.3.0
  provider: ^6.0.0
  flutter_pdfview: ^1.2.5
  video_player: ^2.7.2
  firebase_auth: ^5.4.0
  shared_preferences: ^2.3.5
  path_provider: ^2.1.5
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/data/courses.json
    - assets/data/quizzes.json
    - assets/images/
    - assets/lessons/flutter_theming.pdf
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

